# Generated by Django 4.0.2 on 2022-10-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_smart',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumption.user_table'),
        ),
    ]
