# Generated by Django 4.0.2 on 2022-10-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_device_smart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_smart',
            old_name='name',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='device_smart',
            name='device_type',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='device_smart',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
