# Generated by Django 4.0.2 on 2022-10-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0005_consumption_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption_calc',
            name='number_of_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='treek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumption.user_table')),
            ],
        ),
    ]
